# Book settings
title: Introduction to Data Science SG
author: Daniel
logo: images/logo.png

html:
  favicon: images/favicon.ico

repository: 
    url: https://github.com/ddanieltan/introduction_to_datascience_sg

# launch_buttons:
#     binderhub_url: "https://mybinder.org/v2/gh/ddanieltan/introduction_to_datascience_sg/master?urlpath=lab"

